### ISSUE TITLE
Problem with Demo Model

### ISSUE THREAD

**Issue by namngu** [kevinjliang/tf-Faster-RCNN#15]
Hello,

thank you very much for your work. I am also a very beginner to deep learning and programming with python and tensorflow (but i am not a beginner with programming) and cannot get your demo "faster_rcnn_conv5" to run [log-file.txt](https://github.com/kevinjliang/tf-Faster-RCNN/files/1153669/log-file.txt). Since my resources are very restricted i can only use CPUs. 

--> So my first question is, whether it is possible to get your demo code runnuing with only CPUs? I do not need training; testing would be enough so that i can try to understand the mechanisms in Faster RCNN together with tensorflow.

Using your actual repository and executing the code results in an error regarding 'vram'. I checked out an older commit to resolve this problem (using your answer in another issue) but then experienced another problem. 

--> My second question: Would it be possible for you to reupload a full functional demo using neither cpu or gpu? It would be very helpful for newcomers like me, since tensorflow is more and more getting powerful with tensorflow-slim and since Faster R-CNN is a wonderful algorithm :) It would clearly help my scientific work (i am doing a master thesis right now).

Thank you!

Regards
Nam

**Comment by kevinjliang** [comment]
Hi Nam,

I haven't tested it on CPU only, but I do believe the code was written to work for both. You just have to tweak the TensorFlow installation instructions to download the CPU version instead of the GPU version. That said, we don't have any pre-trained weights for the full model available for download. The model will output garbage unless it's trained, and without a GPU, that may be a bit difficult for Faster RCNN. 

We are aware that the dependency to one of the submodules is currently broken (causing the VRAM error), but I'm currently away interning, so I can only provide limited support to this repo for the time being. However, if you're a TensorFlow beginner, I have been preparing [materials for a TensorFlow workshop](https://github.com/kevinjliang/Duke-Tsinghua-MLSS-2017) that may be of interest. There are some basic models in there that don't need a GPU to train, so I'd highly recommend taking a look. (:

**Comment by namngu** [comment]
Thank you for your fast response... i will try to get my hands on some GPUs and will try out your code again :) my interest is headed towards the implementation of the RPN, which i cannot under since there are so many scripts, which make things complex. I will checkout your materials for basic understanding.

**Comment by zhuanghongjie** [comment]
ts
